Repository Afordin/hackafor-2, pull requests merged in 2024-04, with the labels that each got.

#55 Feature / Code quality updates
  .github/PULL_REQUEST_TEMPLATE.md
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.mjs
  lint-staged.config.mjs
  package.json
  pnpm-lock.yaml
  src/components/Buttons/BurgerButton/BurgerButton.tsx
Labels: enhancement

#50 Feature / Improve hero responsive text
  src/index.css
  src/pages/Home.tsx
  src/pages/_sections/CTA.tsx
  src/pages/_sections/Hero.tsx
  uno.config.ts
Labels: enhancement

#53 Feature / Improve responsive information section
  src/components/Cards/SimpleCard/SimpleCard.tsx
  src/pages/_sections/Information.tsx
Labels: enhancement

#59 Feature / Tag Component
  src/common/constants/index.ts
  src/common/constants/tag.ts
  src/components/Tag/Tag.tsx
  src/components/index.ts
Labels: enhancement

#75 docs(README): :memo: update from npm to pnpm
  README.md
Labels: documentation, enhancement

#74 Feature / Add toggle button group component
  src/components/Buttons/ToggleButtonGroup/ToggleButtonGroup.tsx
  src/components/Buttons/index.ts
  src/pages/Projects/Projects.tsx
Labels: enhancement

#76 Feature: Add project cards
  src/components/Buttons/ToggleButtonGroup/ToggleButtonGroup.tsx
  src/components/Cards/CardWrapper/CardWrapper.tsx
  src/components/Cards/ProjectCard/ProjectCard.tsx
  src/components/Cards/index.ts
  src/components/Tag/Tag.tsx
  src/index.css
  src/pages/Projects/Projects.tsx
  src/pages/Projects/types.ts
Labels: enhancement

#77 Add a countdown to Hackafor day
  src/components/Countdown/Countdown.tsx
  src/components/index.ts
  src/pages/_sections/Information.tsx
Labels: enhancement

#84 docs(pr-template): 📝 update pr template from spanish to english
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-failing-test.yml
  .github/ISSUE_TEMPLATE/3-docs-bug.yml
  .github/ISSUE_TEMPLATE/4-feature-request.yml
  .github/ISSUE_TEMPLATE/5-enhancement-request.yml
  .github/ISSUE_TEMPLATE/6-security-report.yml
  .github/ISSUE_TEMPLATE/7-question-support.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/labels.yml
  .github/workflows/ci.yml
  .github/workflows/commitlint.yml
  .github/workflows/labels.yml
  docs/CODE_OF_CONDUCT.md
Labels: enhancement

#87 Feature: update contributors section
  src/components/Navigation/Nav.tsx
  src/index.css
  src/pages/_sections/Contributors.tsx
Labels: Type: Enhancement

#83 Feat: Add the countdown account in the Hero component
  src/components/Countdown/Countdown.tsx
  src/pages/_sections/Hero.tsx
  src/pages/_sections/Information.tsx
Labels: Design

#93 Feature: general changes
  src/App.tsx
  src/common/constants/components/avatar.ts
  src/common/constants/components/button.ts
  src/common/constants/components/carousel.ts
  src/common/constants/components/index.ts
  src/common/constants/components/spinner.ts
  src/common/constants/components/tag.ts
  src/common/constants/general.ts
  src/common/constants/index.ts
  src/common/hooks/index.ts
  src/common/hooks/useAuth/useAuth.ts
  src/common/hooks/useTwitchStatus/useTwitchStatus.ts
  src/common/utils/index.ts
  src/common/utils/jsVanilla/useCarouselEffect.ts
  src/common/utils/supabase.ts
  src/components/Avatar/Avatar.tsx
  src/components/Buttons/Button/Button.tsx
  src/components/Buttons/ToggleButtonGroup/ToggleButtonGroup.tsx
  src/components/Carousel/Carousel.tsx
  src/components/Countdown/Countdown.tsx
  src/components/Footer/Footer.tsx
  src/components/Logo/Logo.tsx
  src/components/Navigation/Nav.tsx
  src/components/Spinner/Spinner.tsx
  src/components/TwitchLive/TwitchLive.tsx
  src/components/index.ts
  src/data/index.ts
  src/data/legacy/FeatureProjects.ts
  src/data/legacy/README.md
  src/index.css
  src/pages/Projects/Projects.tsx
  src/pages/_sections/CTA.tsx
  src/pages/_sections/FeatureProjects.tsx
  src/pages/_sections/Hero.tsx
  src/pages/_sections/Ticket.tsx
  src/utils/controller/project.controller.ts
Labels: Type: Enhancement, Conflict Detected

#97 Page 404 resolving conflicts
  src/App.tsx
  src/common/constants/routes.ts
  src/index.css
  src/pages/NotFound/NotFound.tsx
Labels: Type: Feature

#96 feat: reusable popover component & participants tags unified into roles
  package.json
  pnpm-lock.yaml
  src/common/constants/components/index.ts
  src/common/constants/components/popover.ts
  src/common/utils/index.ts
  src/common/utils/parser/groupParticipantsByRole.ts
  src/common/utils/utils.ts
  src/components/Cards/ProjectCard/ProjectCard.tsx
  src/components/Popover/Popover.tsx
  src/components/Portal/Portal.tsx
  src/components/Tag/Tag.tsx
  src/components/index.ts
Labels: Type: Feature

#92 Action for contact button when user is not logged in
  src/components/Cards/ProjectCard/ProjectCard.tsx
  src/pages/Projects/Projects.tsx
Labels: Design, Type: Enhancement

#104 style(components/footer): update html entities
  src/components/Footer/Footer.tsx
Labels: Type: Feature

#109 Feature/zyruks/improvement registration page
  src/common/constants/index.ts
  src/common/constants/inputs.ts
  src/common/types/index.ts
  src/common/types/input.ts
  src/common/types/models/Projects.ts
  src/components/Buttons/Button/Button.tsx
  src/components/Counter/Counter.tsx
  src/components/Inputs/TextInput/TextInput.tsx
  src/components/Inputs/Textarea/Textarea.tsx
  src/components/Inputs/index.ts
  src/components/index.ts
  src/pages/Registration/components/RoleSelector.tsx
  src/pages/Registration/components/index.ts
  src/pages/Registration/index.tsx
  src/pages/Registration/utils/index.ts
  src/pages/Registration/utils/roleManagement.ts
  src/utils/schema/projectData.schema.ts
Labels: Type: Enhancement
